from global_objects import JOBTAKERS_BINDKEY, JOBMAKERS_BINDKEY, JOBTAKER_PASSWORDS_BINDKEY, JOBMAKER_PASSWORDS_BINDKEY, JOBS_BINDKEY, LOGS_BINDKEY, DB_PATH
from datetime import timedelta

SECRET_KEY = "epstein grape chiggers"

SQLALCHEMY_DATABASE_URI = f"{DB_PATH}jobs"
SQLALCHEMY_BINDS = {
    JOBTAKERS_BINDKEY: f"{DB_PATH}users",
    JOBMAKERS_BINDKEY: f"{DB_PATH}users",
    JOBTAKER_PASSWORDS_BINDKEY: f"{DB_PATH}passwords",
    JOBMAKER_PASSWORDS_BINDKEY: f"{DB_PATH}passwords",
    JOBS_BINDKEY: f"{DB_PATH}jobs",
    LOGS_BINDKEY: f"{DB_PATH}logs"
}

SQLALCHEMY_TRACK_MODIFICATIONS = False

REMEMBER_COOKIE_DURATION = timedelta(weeks=5)
PERMANENT_SESSION_LIFETIME = timedelta(weeks=5)

REMEMBER_COOKIE_REFRESH_EACH_REQUEST = True
SESSION_REFRESH_EACH_REQUEST = True

MAIL_SERVER = 'smtp.gmail.com'
MAIL_PORT = 587
MAIL_USE_TLS = True
MAIL_USE_SSL = False
MAIL_USERNAME = "teenquest.prod@gmail.com"
MAIL_PASSWORD = "vzvg alzt vabh eusa"
