"""empty message

Revision ID: 7a5eaf9db7c5
Revises: 98a1c3259759
Create Date: 2026-02-04 17:23:37.166310

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '7a5eaf9db7c5'
down_revision = '98a1c3259759'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('job')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('job',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('jobtaker_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('jobmaker_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('jobmaker_rating', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('job_state', postgresql.ENUM('CREATED', 'ACCEPTED_TAKER', 'ACCEPTED_MAKER', 'STARTED', 'ENDED', 'PAYED', name='jobstate'), autoincrement=False, nullable=False),
    sa.Column('date_time_created', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('date_time_accepted_taker', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('date_time_accepted_maker', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('date_time_started', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('date_time_ended', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('date_time_payed', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('job_type', sa.VARCHAR(length=30), autoincrement=False, nullable=False),
    sa.Column('date_time_scheduled_start', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('date_time_scheduled_end', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('country', sa.VARCHAR(length=2), autoincrement=False, nullable=False),
    sa.Column('city', sa.VARCHAR(length=200), autoincrement=False, nullable=False),
    sa.Column('zip_code', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('street', sa.VARCHAR(length=200), autoincrement=False, nullable=False),
    sa.Column('job_title', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('job_description', sa.VARCHAR(length=500), autoincrement=False, nullable=False),
    sa.Column('job_salary', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('job_pkey'))
    )
    # ### end Alembic commands ###
